// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPIntegradorProgIII.DBContexts;

#nullable disable

namespace TPIntegradorProgIII.Migrations
{
    [DbContext(typeof(TPContext))]
    partial class TPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("MeetSwimmer", b =>
                {
                    b.Property<int>("MeetsAttendedId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipantSwimmersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MeetsAttendedId", "ParticipantSwimmersId");

                    b.HasIndex("ParticipantSwimmersId");

                    b.ToTable("ParticipantSwimmersInMeets", (string)null);

                    b.HasData(
                        new
                        {
                            MeetsAttendedId = 2,
                            ParticipantSwimmersId = 1
                        },
                        new
                        {
                            MeetsAttendedId = 1,
                            ParticipantSwimmersId = 1
                        });
                });

            modelBuilder.Entity("SwimmerTrial", b =>
                {
                    b.Property<int>("RegisteredSwimmersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrialsAttendedId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RegisteredSwimmersId", "TrialsAttendedId");

                    b.HasIndex("TrialsAttendedId");

                    b.ToTable("RegisteredSwimmersInTrials", (string)null);

                    b.HasData(
                        new
                        {
                            RegisteredSwimmersId = 1,
                            TrialsAttendedId = 1
                        },
                        new
                        {
                            RegisteredSwimmersId = 1,
                            TrialsAttendedId = 2
                        });
                });

            modelBuilder.Entity("TPIntegradorProgIII.Entities.Meet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MeetDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeetPlace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Meets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MeetDate = "20/12/2022",
                            MeetName = "MeetPiola",
                            MeetPlace = "Piolalandia"
                        },
                        new
                        {
                            Id = 2,
                            MeetDate = "25/12/2022",
                            MeetName = "MeetPiola2",
                            MeetPlace = "Piolalandia"
                        });
                });

            modelBuilder.Entity("TPIntegradorProgIII.Entities.Trial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Distance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MeetId");

                    b.ToTable("Trials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Distance = 100,
                            MeetId = 1,
                            Style = "Croll"
                        },
                        new
                        {
                            Id = 2,
                            Distance = 150,
                            MeetId = 2,
                            Style = "Croll"
                        });
                });

            modelBuilder.Entity("TPIntegradorProgIII.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("User");
                });

            modelBuilder.Entity("TPIntegradorProgIII.Entities.Swimmer", b =>
                {
                    b.HasBaseType("TPIntegradorProgIII.Entities.User");

                    b.HasDiscriminator().HasValue("Swimmer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "nbologna31@gmail.com",
                            Name = "Nicolas",
                            Password = "ba3253876aed6bc22d4a6ff53d8406c6ad864195ed144ab5c87621b6c233b548baeae6956df346ec8c17f5ea10f35ee3cbc514797ed7ddd3145464e2a0bab413",
                            Surname = "Bologna"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Jperez@gmail.com",
                            Name = "Juan",
                            Password = "ba3253876aed6bc22d4a6ff53d8406c6ad864195ed144ab5c87621b6c233b548baeae6956df346ec8c17f5ea10f35ee3cbc514797ed7ddd3145464e2a0bab413",
                            Surname = "Perez"
                        },
                        new
                        {
                            Id = 3,
                            Email = "pgarcia@gmail.com",
                            Name = "Pedro",
                            Password = "ba3253876aed6bc22d4a6ff53d8406c6ad864195ed144ab5c87621b6c233b548baeae6956df346ec8c17f5ea10f35ee3cbc514797ed7ddd3145464e2a0bab413",
                            Surname = "Garcia"
                        });
                });

            modelBuilder.Entity("MeetSwimmer", b =>
                {
                    b.HasOne("TPIntegradorProgIII.Entities.Meet", null)
                        .WithMany()
                        .HasForeignKey("MeetsAttendedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPIntegradorProgIII.Entities.Swimmer", null)
                        .WithMany()
                        .HasForeignKey("ParticipantSwimmersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwimmerTrial", b =>
                {
                    b.HasOne("TPIntegradorProgIII.Entities.Swimmer", null)
                        .WithMany()
                        .HasForeignKey("RegisteredSwimmersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPIntegradorProgIII.Entities.Trial", null)
                        .WithMany()
                        .HasForeignKey("TrialsAttendedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TPIntegradorProgIII.Entities.Trial", b =>
                {
                    b.HasOne("TPIntegradorProgIII.Entities.Meet", "Meet")
                        .WithMany("Trials")
                        .HasForeignKey("MeetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meet");
                });

            modelBuilder.Entity("TPIntegradorProgIII.Entities.Meet", b =>
                {
                    b.Navigation("Trials");
                });
#pragma warning restore 612, 618
        }
    }
}
